concurrency:
  cancel-in-progress: true
  group: ${{ (github.ref == 'refs/heads/branch_1.2.18' || github.ref == 'refs/heads/main'
    || github.ref == 'refs/heads/release' ) && format('ci-main-{0}', github.sha) ||
    format('ci-main-{0}', github.ref) }}
jobs:
  Test:
    name: JDK ${{ matrix.jdk }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 50
    - continue-on-error: true
      if: ${{ matrix.jdk != '8' }}
      name: Set up Java ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Install
      run: mvn -B install
    strategy:
      fail-fast: true
      matrix:
        jdk:
        - 11
        - 17
        - 19
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
      max-parallel: 4
name: CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
permissions:
  contents: read
